version: '3'
services:
  bot:
    build: .
    container_name: "webster"
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongodb:27017/webster
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null